---
- name: create cluster
  local_action:
    module: vmware_cluster
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.pwd }}"
    validate_certs: False
    datacenter_name: "{{ dc }}"
    cluster_name: "{{ item }}"
  with_items:
    - "{{ clusters }}"
