---
- name: create cluster
  local_action:
    module: vmware_cluster
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.pwd }}"
    validate_certs: False
    datacenter_name: "{{ vcenter.dc.name }}"
    cluster_name: "{{ vcenter.dc.cluster.name }}"
    enable_ha: "{{ vcenter.dc.cluster.ha }}"
    enable_drs: "{{ vcenter.dc.cluster.drs }}"
