---
- name: Create Datacenter
  local_action:
    module: vmware_datacenter
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.pwd }}"
    validate_certs: False
    datacenter_name: "{{ vcenter.dc.name }}"
    state: present
