- name: Add ESXi Host to VCSA
  local_action:
    module: vmware_host
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.pwd }}"
    datacenter_name: "{{ vcenter.dc.name }}"
    validate_certs: False
    cluster_name: "{{ vcenter.dc.cluster.name }}"
    esxi_hostname: "{{ vcenter.dc.cluster.hosts.{{ item }}.name }}"
    esxi_username: "{{ vcenter.dc.cluster.hosts.{{ item }}.user }}"
    esxi_password: "{{ vcenter.dc.cluster.hosts.{{ item }}.pwd }}"
    state: present
  with_items:
    -  "{{ vcenter.dc.cluster.hosts }}"
