- name: Add ESXi Host to VCSA
  local_action:
    module: vmware_host
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.pwd }}"
    datacenter_name: "{{ dc }}"
    validate_certs: False
    cluster_name: "{{ clusters.1 }}"
    esxi_hostname: "{{ item }}"
    esxi_username: "{{ hosts_user }}"
    esxi_password: "{{ hosts_pwd }}"
    state: present
  with_items:
    -  "{{ hosts }}"
