---
- name: Create VM
  vmware_guest:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.pwd }}"
    validate_certs: False
    esxi_hostname: "{{ hosts.1 }}"
    datacenter: "{{ dc }}"
    state: poweredon
    name: "{{ item }}"
    template: "{{ template_name.0 }}"
  with_items:
    - "{{ vm_name }}"
