---
- vsphere_guest:
    vcenter_hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.pwd }}"
    validate_certs: True
    guest: "{{ vm_name.0 }}"
    from_template: yes
    template_src: "{{ template_name.0 }}"
    cluster: "{{ clusters.1 }}"
    esxi: "{{ hosts.1 }}"
    state: present
